# Generated by Django 3.0.4 on 2020-04-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200423_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielinks',
            name='type',
            field=models.CharField(choices=[('Downalod link', 'Downalod link'), ('Watch link', 'Watch link')], max_length=100),
        ),
    ]
