# Generated by Django 3.0.4 on 2020-04-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200424_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielinks',
            name='type',
            field=models.CharField(choices=[('D', 'Downalod link'), ('W', 'Watch link')], max_length=1),
        ),
    ]
