# Generated by Django 3.0.4 on 2020-04-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_movie_bannner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='bannner',
            new_name='banner',
        ),
    ]
